spring:
  application:
    name: QuickCourt-Backend

  datasource:
    url: jdbc:mysql://quickcourt-quickcourt.c.aivencloud.com:26189/defaultdb?ssl-mode=REQUIRED
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:password123}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  security:
    user:
      name: ${ADMIN_USER:admin}
      password: ${ADMIN_PASSWORD:admin123}
      roles: ADMIN,USER

  eureka:
    client:
      service-url:
        defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
    instance:
      preferIpAddress: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

otp:
  expiry: 300000
  length: 6
  max-attempts: 3

server:
  port: ${SERVER_PORT:8080}

jwt:
  secret: ${JWT_SECRET}
  expiry: ${JWT_EXPIRY:3600000}
  refreshExpiry: ${JWT_REFRESH_EXPIRY:86400000}

cookie:
  expiry: ${COOKIE_EXPIRY:3600}
