spring:
  application:
    name: QuickCourt-Backend

  datasource:
    url: jdbc:mysql://localhost:3306/odoo
    username: root
    password: Realme6G90T

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update

  security:
    user:
      name: admin
      password: admin123
      roles: ADMIN,USER
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
    instance:
      preferIpAddress: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: rapoluvenky8@gmail.com
    password: caek hhhj ynow vmdn
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

jwt:
  secret: your_super_secret_jwt_key_at_least_64_characters_long
  expiry: 86400000

otp:
  expiry: 300000
  length: 6
  max-attempts: 3

cookie:
  expiry: 3600

server:
  port: 8080